### PR TITLE
Correct README spelling typos

### PR DESCRIPTION
**Pull request by hugetim**
licence -> license

### CODE REVIEW

**Comment by hugetim** [comment]
I'm not needing credit for this if it's easier to do the change directly. :)

**Comment by meredydd** [comment]
Fun fact: Anvil's house style is British English for documentation and public-facing web pages. It's one of the quirks we allow ourselves ;) In British English, "licence" is the correct spelling for the noun, but "license" for the verb. Or, as an aide-memoire:

image

**Comment by hugetim** [comment]
I had no idea that was the British spelling (and I even studied abroad for a year at UCL). My mistake.

**Comment by hugetim** [comment]
For other confused Yanks, I found [this](https://www.oxfordreference.com/display/10.1093/acref/9780199545155.001.0001/acref-9780199545155-appendix-010;jsessionid=71FDFE0E23EBBDA71E0EC3C4FD31AB28) summary of British-American spelling differences helpful. I was only aware of half of them, to my surprise.

**Pull request closed without merging**
